version: '3.8'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    ports:
        - $MONGODB_PORT:$MONGODB_DOCKER_PORT
  app:
    depends_on:
      - mongodb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_PORT:$NODE_DOCKER_PORT

